# Generated by Django 4.1.1 on 2022-10-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magasinier",
            name="pays",
            field=models.CharField(
                choices=[
                    ("BF", "Burkina Faso"),
                    ("GH", "Ghana"),
                    ("CI", "Côte d'Ivoire"),
                    ("CH", "Chine"),
                ],
                max_length=255,
            ),
        ),
    ]
