# Generated by Django 4.1.1 on 2022-10-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_magasinier_pays"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=16)),
                (
                    "pays",
                    models.CharField(
                        choices=[
                            ("BF", "Burkina Faso"),
                            ("GH", "Ghana"),
                            ("CI", "Côte d'Ivoire"),
                            ("CH", "Chine"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={"ordering": ["id", "nom", "prenom"],},
        ),
        migrations.AlterModelOptions(
            name="magasinier", options={"ordering": ["id", "nom", "prenom"]},
        ),
        migrations.RemoveField(model_name="magasinier", name="pays",),
        migrations.AddField(
            model_name="magasinier",
            name="email",
            field=models.EmailField(default="username@gmail.com", max_length=255),
        ),
    ]
