# Generated by Django 4.1.1 on 2022-10-15 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pieces", "0001_initial"),
        ("stock", "0003_fournisseur_alter_magasinier_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Magasin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("dateCreation", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={"ordering": ["id", "nom"],},
        ),
        migrations.CreateModel(
            name="PieceStockées",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantiteStockee", models.IntegerField(default=0)),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pieces.piece"
                    ),
                ),
            ],
            options={"ordering": ["id", "piece"],},
        ),
    ]
