# Generated by Django 4.1.1 on 2022-10-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_magasin_piecestockées"),
    ]

    operations = [
        migrations.RenameModel(old_name="Magasinier", new_name="Gerant",),
    ]
