# Generated by Django 4.1.1 on 2022-10-15 15:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_rename_magasinier_gerant"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandeFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numCommande", models.CharField(max_length=250, unique=True)),
                ("dateCommande", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.fournisseur",
                    ),
                ),
                (
                    "gerant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.gerant"
                    ),
                ),
            ],
            options={"ordering": ["id"],},
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numFacture", models.CharField(max_length=12, unique=True)),
                ("total", models.FloatField(default=0)),
                (
                    "commandeFournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.commandefournisseur",
                    ),
                ),
            ],
            options={"ordering": ["id"],},
        ),
        migrations.CreateModel(
            name="PaiementFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montantPaye", models.FloatField(default=0)),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.facture"
                    ),
                ),
            ],
            options={"ordering": ["id"],},
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantiteCommande", models.IntegerField(default=0)),
                ("quantiteRecu", models.IntegerField(default=0)),
                (
                    "commandeFournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.commandefournisseur",
                    ),
                ),
                (
                    "pieceStockées",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.piecestockées",
                    ),
                ),
            ],
            options={"ordering": ["id"],},
        ),
        migrations.CreateModel(
            name="InfosSortie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField(default=0)),
                ("prixSortie", models.FloatField(default=0)),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.magasin"
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.piecestockées",
                    ),
                ),
            ],
            options={"ordering": ["id", "piece"],},
        ),
    ]
