# Generated by Django 4.1.1 on 2022-10-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pieces", "0002_alter_categorie_options_alter_piece_options"),
        ("stock", "0006_commandefournisseur_facture_paiementfournisseur_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="PieceStockées", new_name="PieceStockée",),
        migrations.RenameField(
            model_name="lignecommande",
            old_name="pieceStockées",
            new_name="pieceStockée",
        ),
    ]
