# Generated by Django 4.1.1 on 2022-10-18 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pieces", "0002_alter_categorie_options_alter_piece_options"),
        ("stock", "0007_rename_piecestockées_piecestockée_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gerant", name="email", field=models.EmailField(max_length=255),
        ),
        migrations.CreateModel(
            name="QuantitéStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantiteStockee", models.IntegerField(default=0)),
                ("prix", models.FloatField(default=0)),
                (
                    "magasin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.magasin"
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pieces.piece"
                    ),
                ),
            ],
            options={"ordering": ["id", "piece", "magasin"],},
        ),
    ]
