# Generated by Django 4.0.6 on 2022-10-18 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_gerant_email_quantitéstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id', 'intitule', '-dateCreation'],
            },
        ),
        migrations.AlterModelOptions(
            name='commandefournisseur',
            options={'ordering': ['id', 'gerant', 'fournisseur', 'numCommande', 'dateCommande']},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['id', 'numFacture', 'total', 'commandeFournisseur']},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['id', 'nom', 'prenom', 'telephone', 'pays']},
        ),
        migrations.AlterModelOptions(
            name='gerant',
            options={'ordering': ['id', 'nom', 'prenom', 'telephone', 'email']},
        ),
        migrations.AlterModelOptions(
            name='infossortie',
            options={'ordering': ['id', 'piece', 'magasin', 'quantite', 'prixSortie']},
        ),
        migrations.AlterModelOptions(
            name='lignecommande',
            options={'ordering': ['id', 'commandeFournisseur', 'quantiteCommande', 'quantiteRecu']},
        ),
        migrations.AlterModelOptions(
            name='magasin',
            options={'ordering': ['id', 'nom', '-dateCreation']},
        ),
        migrations.AlterModelOptions(
            name='paiementfournisseur',
            options={'ordering': ['id', 'montantPaye', 'facture']},
        ),
        migrations.AlterModelOptions(
            name='piecestockée',
            options={'ordering': ['id', 'designation', 'quantiteStockee', 'categorie']},
        ),
        migrations.AlterModelOptions(
            name='quantitéstock',
            options={'ordering': ['id', 'piece', 'magasin', 'prix']},
        ),
        migrations.RemoveField(
            model_name='piecestockée',
            name='piece',
        ),
        migrations.AddField(
            model_name='magasin',
            name='listPieceEntree',
            field=models.ManyToManyField(related_name='magasinEntree', through='stock.QuantitéStock', to='stock.piecestockée'),
        ),
        migrations.AddField(
            model_name='magasin',
            name='listPieceSortie',
            field=models.ManyToManyField(related_name='magasinSortie', through='stock.InfosSortie', to='stock.piecestockée'),
        ),
        migrations.AddField(
            model_name='piecestockée',
            name='designation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='dateCommande',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='magasin',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quantitéstock',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.piecestockée'),
        ),
        migrations.AddField(
            model_name='piecestockée',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.categorie'),
            preserve_default=False,
        ),
    ]
