# Generated by Django 4.0.6 on 2022-10-18 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0001_initial'),
        ('stock', '0009_categorie_alter_commandefournisseur_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandefournisseur',
            name='exercice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commande_fournisseur', to='exercices.exercice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_commande', to='stock.fournisseur'),
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='gerant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_commande', to='stock.gerant'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='commandeFournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_facture', to='stock.commandefournisseur'),
        ),
        migrations.AlterField(
            model_name='infossortie',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_sortie', to='stock.magasin'),
        ),
        migrations.AlterField(
            model_name='infossortie',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_sortie', to='stock.piecestockée'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='commandeFournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_ligneCommande', to='stock.commandefournisseur'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='pieceStockée',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_ligneCommande', to='stock.piecestockée'),
        ),
        migrations.AlterField(
            model_name='paiementfournisseur',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='stock.facture'),
        ),
        migrations.AlterField(
            model_name='piecestockée',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='stock.categorie'),
        ),
        migrations.AlterField(
            model_name='quantitéstock',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_quantite', to='stock.magasin'),
        ),
        migrations.AlterField(
            model_name='quantitéstock',
            name='piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_local', to='stock.piecestockée'),
        ),
    ]
