# Generated by Django 4.1.1 on 2022-10-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pieces", "0002_alter_categorie_options_alter_piece_options"),
        ("stock", "0010_commandefournisseur_exercice_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="piecestockée", name="categorie",),
        migrations.RemoveField(model_name="lignecommande", name="pieceStockée",),
        migrations.AddField(
            model_name="lignecommande",
            name="piece",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info_ligneCommande",
                to="pieces.piece",
            ),
        ),
        migrations.AlterField(
            model_name="infossortie",
            name="piece",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info_sortie",
                to="pieces.piece",
            ),
        ),
        migrations.AlterField(
            model_name="magasin",
            name="listPieceEntree",
            field=models.ManyToManyField(
                related_name="magasinEntree",
                through="stock.QuantitéStock",
                to="pieces.piece",
            ),
        ),
        migrations.AlterField(
            model_name="magasin",
            name="listPieceSortie",
            field=models.ManyToManyField(
                related_name="magasinSortie",
                through="stock.InfosSortie",
                to="pieces.piece",
            ),
        ),
        migrations.AlterField(
            model_name="quantitéstock",
            name="piece",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info_local",
                to="pieces.piece",
            ),
        ),
    ]
