# Generated by Django 4.1.1 on 2022-10-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0011_remove_piecestockée_categorie_and_more"),
        ("ventes", "0002_alter_commandclient_piecevendue_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="PieceStockée",),
    ]
