# Generated by Django 4.1.1 on 2022-10-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pieces", "0002_alter_categorie_options_alter_piece_options"),
        ("stock", "0012_delete_piecestockée"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lignecommande",
            name="piece",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info_ligneCommande",
                to="pieces.piece",
            ),
        ),
    ]
