# Generated by Django 4.1.1 on 2022-11-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0014_magasin_gerant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandefournisseur",
            name="numCommande",
            field=models.SlugField(),
        ),
    ]
