# Generated by Django 4.1.1 on 2022-11-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0018_alter_commandefournisseur_gerant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandefournisseur",
            name="numCommande",
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
