# Generated by Django 4.1.1 on 2022-11-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0019_alter_commandefournisseur_numcommande"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commandefournisseur",
            options={"ordering": ["id", "gerant", "fournisseur", "dateCommande"]},
        ),
        migrations.RemoveField(model_name="commandefournisseur", name="numCommande",),
    ]
