# Generated by Django 4.1.1 on 2022-11-04 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock", "0021_commandefournisseur_numcommande"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commandefournisseur",
            options={
                "ordering": [
                    "id",
                    "gerant",
                    "fournisseur",
                    "numCommande",
                    "dateCommande",
                ]
            },
        ),
        migrations.AlterField(
            model_name="magasin",
            name="gerant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gerant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
