# Generated by Django 4.1.1 on 2022-11-04 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock", "0022_alter_commandefournisseur_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="magasin",
            options={"ordering": ["id", "nom", "gerant", "-dateCreation"]},
        ),
        migrations.AlterField(
            model_name="magasin",
            name="gerant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
