# Generated by Django 4.0.8 on 2022-11-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_alter_paiementfournisseur_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infossortie',
            options={'ordering': ['id', 'piece', 'magasin', 'quantite']},
        ),
        migrations.RemoveField(
            model_name='infossortie',
            name='prixSortie',
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='prixSortie',
            field=models.FloatField(default=1),
        ),
    ]
