# Generated by Django 4.1.1 on 2022-10-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pieces", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorie", options={"ordering": ["id", "intitule"]},
        ),
        migrations.AlterModelOptions(
            name="piece", options={"ordering": ["id", "designation"]},
        ),
    ]
