# Generated by Django 4.1.1 on 2022-11-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercice",
            name="fin",
            field=models.DateField(blank=True, unique=True),
        ),
    ]
