# Generated by Django 4.1.1 on 2022-11-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercices", "0002_alter_exercice_fin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercice",
            name="fin",
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
