# Generated by Django 4.0.6 on 2022-10-18 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0009_categorie_alter_commandefournisseur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=100)),
                ('prenom_agent', models.CharField(max_length=100)),
                ('telephone_agent', models.CharField(max_length=10)),
                ('email_agent', models.EmailField(max_length=254, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation', 'nom_agent', 'prenom_agent', 'email_agent'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(max_length=100)),
                ('telephone_client', models.CharField(max_length=10)),
                ('estBonClient', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation', 'nom_client', 'prenom_client'],
            },
        ),
        migrations.CreateModel(
            name='CommandClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCommande', models.CharField(max_length=100, unique=True)),
                ('totalCommande', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_commande', to='ventes.client')),
            ],
            options={
                'ordering': ['-date_creation', 'numCommande', 'totalCommande'],
            },
        ),
        migrations.CreateModel(
            name='FactureClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numFacture', models.CharField(max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='ventes.commandclient')),
            ],
            options={
                'ordering': ['-date_creation', 'numFacture'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='ventes.factureclient')),
            ],
            options={
                'ordering': ['-date_creation', 'montant'],
            },
        ),
        migrations.CreateModel(
            name='InfosCommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infosCommande', to='ventes.commandclient')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infosCommande', to='stock.piecestockée')),
            ],
            options={
                'ordering': ['-date_creation', 'quantite', 'prix_unitaire'],
            },
        ),
        migrations.AddField(
            model_name='commandclient',
            name='pieceVendue',
            field=models.ManyToManyField(through='ventes.InfosCommandeClient', to='stock.piecestockée'),
        ),
        migrations.AddField(
            model_name='commandclient',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_commande', to='ventes.agentcommercial'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('nom_client', 'prenom_client', 'telephone_client'), name='Unique_client_constraint'),
        ),
        migrations.AddField(
            model_name='agentcommercial',
            name='magasin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='stock.magasin'),
        ),
    ]
