# Generated by Django 4.1.1 on 2022-10-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pieces", "0002_alter_categorie_options_alter_piece_options"),
        ("ventes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandclient",
            name="pieceVendue",
            field=models.ManyToManyField(
                through="ventes.InfosCommandeClient", to="pieces.piece"
            ),
        ),
        migrations.AlterField(
            model_name="infoscommandeclient",
            name="piece",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="infosCommande",
                to="pieces.piece",
            ),
        ),
    ]
